In [42]:
import numpy as np
import pandas as pd

In [2]:
test = np.array([1,2,3])

In [3]:
test_nested = np.array([test, test, test])

In [4]:
test_nested

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [5]:
test = np.array([1,2,3,4,5])

In [9]:
test[::-1]

array([5, 4, 3, 2, 1])

In [28]:
test[::-1]

array([5, 4, 3, 2, 1])

In [40]:
test = test[::-1]

In [41]:
test

array([5, 4, 3, 2, 1])

In [46]:
testrow = [[test, test, test]]

In [47]:
pd.DataFrame(testrow)

0                1                2
0  [5, 4, 3, 2, 1]  [5, 4, 3, 2, 1]  [5, 4, 3, 2, 1]

In [48]:
test = None

In [50]:
pd.DataFrame(columns = ["test1", "test2", "test3", "test4"])

Empty DataFrame
Columns: [test1, test2, test3, test4]
Index: []